version: 2

build:
  tools:
    os: ubuntu-20.04
    python: "3.10"

sphinx:
  configuration: docs/conf.py


python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
