# ytdl-sub needs a temporary place to download files. Choose that path here
configuration:
  working_directory: 'tmp'

presets:
  soundcloud_with_id3_tags:
    soundcloud:
      download_strategy: "albums_and_singles"
      skip_premiere_tracks: True
    ytdl_options:
      format: 'bestaudio[ext=mp3]'
    output_options:
      file_name: "[{album_year}] {sanitized_album}/{track_number_padded} - {sanitized_title}.{ext}"
      convert_thumbnail: "jpeg"
      thumbnail_name: "[{album_year}] {sanitized_album}/folder.jpeg"
    metadata_options:
      id3:
        id3_version: "2.4"
        tags:
          artist: "{artist}"
          albumartist: "{artist}"
          title: "{title}"
          album: "{album}"
          tracknumber: "{track_number}"
          year: "{album_year}"
          genre: "{genre}"

  music_videos:
    youtube:
    ytdl_options:
      format: 'best'
      ignoreerrors: True
    output_options:
      file_name: "{sanitized_artist} - {sanitized_title}.{ext}"
      convert_thumbnail: "jpeg"
      thumbnail_name: "{sanitized_artist} - {sanitized_title}.jpeg"
    metadata_options:
      nfo:
        nfo_name: "{sanitized_artist} - {sanitized_title}.nfo"
        nfo_root: "musicvideo"
        tags:
          artist: "{artist}"
          title: "{title}"
          album: "Music Videos"
          year: "{upload_year}"

  yt_channel:
    youtube:
    ytdl_options:
      format: 'best'
      ignoreerrors: True
    output_options:
      file_name: "{output_file_name}.{ext}"
      convert_thumbnail: "jpeg"
      thumbnail_name: "{output_file_name}.jpeg"
    metadata_options:
      nfo:
        nfo_name: "{output_file_name}.nfo"
        nfo_root: "episodedetails"
        tags:
          title: "{title}"
          season: "{upload_year}"
          episode: "{upload_month}{upload_day_padded}"
          plot: "{description}"
          year: "{upload_year}"
          aired: "{upload_year}-{upload_month_padded}-{upload_day_padded}"
      output_directory_nfo:
        nfo_name: "tvshow.nfo"
        nfo_root: "tvshow"
        tags:
          title: "{tv_show_name}"
    overrides:
      output_file_name: "Season {upload_year}/s{upload_year}.e{upload_month_padded}{upload_day_padded} - {sanitized_title}"