# ytdl-sub needs a temporary place to download files. Choose that path here
working_directory: 'tmp'

presets:
  soundcloud_with_id3_tags:
    soundcloud:
      download_strategy: "albums_and_singles"
      skip_premiere_tracks: True
    ytdl_options:
      format: 'bestaudio[ext=mp3]'
    post_process:
      file_name: "[{album_year}] {sanitized_album}/{track_number_padded} - {sanitized_title}.{ext}"
      thumbnail_name: "[{album_year}] {sanitized_album}/folder.{thumbnail_ext}"
      tagging:
        artist: "{artist}"
        albumartist: "{artist}"
        title: "{title}"
        album: "{album}"
        tracknumber: "{track_number}"
        year: "{album_year}"
        genre: "{genre}"

  music_videos:
    youtube:
      download_strategy: "playlist"
    ytdl_options:
      format: 'best'
      ignoreerrors: True
    post_process:
      file_name: "{sanitized_artist} - {sanitized_title}.{ext}"
      convert_thumbnail: "jpg"
      thumbnail_name: "{sanitized_artist} - {sanitized_title}.jpg"
      nfo_name: "{sanitized_artist} - {sanitized_title}.nfo"
      nfo_root: "musicvideo"
      nfo:
        artist: "{artist}"
        title: "{title}"
        album: "Music Videos"
        year: "{upload_year}"
