name: ytld-sub build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run linters
      run: |
        pip install .[lint]
        ./tools/linter check
    - name: Run tests
      run: |
        pip install .[test]
        ./tools/test lcov
    - name: Report coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: coverage.lcov
        artifact-name: code-coverage-report
        repo_token: ${{ secrets.GITHUB_TOKEN }}
